### ISSUE TITLE
Backend Server down?

### ISSUE THREAD

**Issue by tropiix** [MustardWallet/MustardWalletLTC#9] opened 2021-04-18 21:03 UTC
Hello,
I've been messing around with the wallet for about 3 hours, and I couldn't get any full connection.
Differents ports have been tried so far, (9050, 9150). None of those work.
If I use Wasabi Wallet It instantly indicates that Tor is running and Backend connection is existing.

I have reinstalled the Mustard Wallet but no success aswell.
I've been trying to get this to work, as when I downloaded it, I already sent coins to the wallet and later realized that I wasn't connected to the Backend / Tor the whole time.

The onion adress is also not reachable via tor. (if that should be reachable)

Edit:
Just figured out, if I'd disable Tor for "debugging" purposes, the backend would connect, although my balance is still saying 0.00 LTC.  I have inserted my transaction hex into the transaction broadcaster but that just prints out an error saying "EndOfStreamException: No more byte to read." I have also tried to do it via a file but that does not work too.

`
2021-04-18 23:14:48 INFO	Global (290)	Start connecting to nodes...
2021-04-18 23:14:48 INFO	Global (314)	Start synchronizing filters...
2021-04-18 23:14:50 ERROR	PeriodicRunner (73)	Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at System.Net.Http.HttpContentExtensions.ReadAsJsonAsync[T](HttpContent me)
   at System.Net.Http.HttpResponseMessageExtensions.ThrowRequestExceptionFromContentAsync(HttpResponseMessage me)
   at WalletWasabi.WebClients.Wasabi.WasabiClient.GetVersionsAsync(CancellationToken cancel)
   at WalletWasabi.WebClients.Wasabi.WasabiClient.CheckUpdatesAsync(CancellationToken cancel)
   at WalletWasabi.Services.UpdateChecker.ActionAsync(CancellationToken cancel)
   at WalletWasabi.Bases.PeriodicRunner.ExecuteAsync(CancellationToken stoppingToken)
2021-04-18 23:14:50 ERROR	WasabiSynchronizer (306)	Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at System.Net.Http.HttpContentExtensions.ReadAsJsonAsync[T](HttpContent me)
   at System.Net.Http.HttpResponseMessageExtensions.ThrowRequestExceptionFromContentAsync(HttpResponseMessage me)
   at WalletWasabi.WebClients.Wasabi.WasabiClient.GetSynchronizeAsync(uint256 bestKnownBlockHash, Int32 count, Nullable`1 estimateMode, CancellationToken cancel)
   at System.Threading.Tasks.TaskExtensions.WithAwaitCancellationAsync[T](Task`1 me, CancellationToken cancel, Int32 waitForGracefulTerminationMilliseconds)
   at WalletWasabi.Services.WasabiSynchronizer.<>c__DisplayClass60_0.<<Start>b__0>d.MoveNext()
2021-04-18 23:14:50 INFO	WalletManager (192)	Starting Wallet...
2021-04-18 23:14:50 INFO	CoinJoinClient (133)	CoinJoinClient is successfully initialized.
2021-04-18 23:14:50 INFO	Wallet (179)	StartAsync finished in 16 milliseconds.
2021-04-18 23:14:50 INFO	WalletManager (194)	Wallet started.
2021-04-18 23:15:04 ERROR	TransactionBroadcasterViewModel (136)	_System.IO.EndOfStreamException:`No more byte to read_

( error on top )

   at NBitcoin.BitcoinStream.ReadWriteBytes(Span`1 data)
   at NBitcoin.BitcoinStream.ReadWrite(Span`1& arr)
   at NBitcoin.uint256.MutableUint256.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinStream.ReadWrite(uint256& value)
   at NBitcoin.OutPoint.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
   at NBitcoin.TxIn.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
   at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data)
   at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data)
   at NBitcoin.BitcoinStream.ReadWrite[TList,TItem](TList& list)
   at NBitcoin.Transaction.ReadWrite(BitcoinStream stream)
   at NBitcoin.Transaction.FromBytes(Byte[] bytes, Nullable`1 version)
   at NBitcoin.Transaction.Load(Byte[] bytes, Nullable`1 version, Network network)
   at NBitcoin.Transaction.Load(Byte[] bytes, Network network)
   at NBitcoin.Transaction.Parse(String hex, Network network)
   at WalletWasabi.Gui.Controls.WalletExplorer.TransactionBroadcasterViewModel.OnDoTransactionBroadcastAsync()
   at WalletWasabi.Gui.Controls.WalletExplorer.TransactionBroadcasterViewModel.<.ctor>b__4_3()
2021-04-18 23:15:10 INFO	MainWindow.xaml (109)	UiConfig is saved.
2021-04-18 23:15:10 WARNING	Global (630)	Process is exiting.
2021-04-18 23:15:10 INFO	WalletManager (356)	KeyManager backup saved to `C:\Users\---\AppData\Roaming\MustardWalletLTC\Client\WalletBackups\---.json`.
2021-04-18 23:15:10 INFO	Wallet (273)	ChaumianClient is stopped.
2021-04-18 23:15:10 INFO	WalletManager (358)	Wallet is stopped.
2021-04-18 23:15:10 INFO	Global (682)	Disposed FeeProviders.
2021-04-18 23:15:10 INFO	Global (689)	CoinJoinProcessor is disposed.
2021-04-18 23:15:10 INFO	Global (696)	Synchronizer is stopped.
2021-04-18 23:15:10 INFO	HostedServices (80)	Stopped Software Update Checker.
2021-04-18 23:15:10 INFO	HostedServices (130)	Disposed Software Update Checker.
2021-04-18 23:15:10 INFO	Global (705)	Stopped background services.
2021-04-18 23:15:10 INFO	Global (716)	AddressManager is saved to `C:\Users\---\AppData\Roaming\MustardWalletLTC\Client\AddressManager\AddressManagerltc-main.dat`.
2021-04-18 23:15:10 INFO	Global (729)	Nodes are disposed.
2021-04-18 23:15:10 INFO	Global (754)	TorManager is stopped.
2021-04-18 23:15:10 INFO	Global (762)	AsyncMutex(es) are stopped.
2021-04-18 23:15:10 INFO	Global (778)	Mustard Wallet for Litecoin stopped gracefully ( --- ).
2021-04-18 23:15:10 INFO	Program (61)	Mustard Wallet for Litecoin GUI stopped gracefully ( --- ).`

This is also a very common issue I tend to get from time to time,
`Apr 18 23:25:35.000 [notice] Bootstrapped 100% (done): Done
Apr 18 23:25:41.000 [notice] Closing stream for '[scrubbed].onion': hidden service is unavailable (try again later).
Apr 18 23:26:00.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.`

I'd be happy If you could evaluate on this. Thank you!

**Comment by gabrielkrieger** [comment] 2021-04-19 09:54
Hi,

Thanks ; I just checked and it turns out the Tor process was down indeed .

It should work now !

My sincerest apologies for the downtime , I have to create a monitoring script for this ...

Thank you for the heads up ,

Gabriel K.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gabrielkrieger** [comment] 2021-04-19 12:45
It's been confirmed to work on https://www.reddit.com/r/MustardWallet/ so I'll close this .

**Closed as completed by gabrielkrieger** 2021-04-19 12:45 UTC
